# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9304c89c6ce81a39a48a8285313bf64df32839392271061308f45827ac1c8254d80434af66000d4aed374b480e65ada1e7c9dfc9a975d567088a9838be76ad3f

test:
  secret_key_base: cb05fb8172bd208964e5017e7185a2a17b0529cda55e8e0ac61e84611f0ce9a7e4c7cdd825eabf32ce086f08e60fcddb58749f56a065e01daa89fad5073f6b82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
